import Head from 'next/head';
import { Menu } from './../components/menu';
import { Header } from '../components/sections/header';
import { Footer } from '../components/sections/footer';
import { FeatureSection } from '../components/sections/features';
import { ProductSection } from '../components/sections/products';
import { SertificateSection } from '../components/sections/sertificates';
import { Contacts } from '../components/sections/contacts';
import styles from '../styles/Home.module.css';

export default function Home() {
    return (
        <>
            <Head>
                <title>Euro Filter</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />

            <main className={styles.main}>
                <Menu />

                <FeatureSection />
                <ProductSection />
                <SertificateSection />
                <Contacts />
                <Footer />
            </main>
        </>
    );
}
